enum Cudd_ReorderingType { 

	CUDD_REORDER_RANDOM, 
	CUDD_REORDER_SIFT, 
	CUDD_REORDER_GROUP_SIFT, 
	CUDD_REORDER_SYMM_SIFT,
	CUDD_REORDER_GROUP_SIFT_CONV,
	CUDD_REORDER_WINDOW2,
	CUDD_REORDER_ANNEALING 
} rd_type;

